/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MindStarMapPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_MINDSTARMAP = "mindstarmap-view";
var DEFAULT_SETTINGS = {
  provider: "deepseek",
  apiKey: "",
  endpointUrl: "",
  modelName: "",
  appId: "",
  apiSecret: "",
  temperature: 0.7,
  maxTokens: 2e3,
  autoScanOnStartup: false,
  autoOrganizeOnStartup: false,
  autoOrganizeOnCreate: false,
  autoOrganizeOnModify: false,
  autoRelationScanAfterOrganize: false,
  batchSize: 5,
  excludeFolders: [],
  insertSummary: false,
  pluginInitialized: false,
  maxRelationsPerNote: 99999,
  enableWebSearch: false,
  maxGeneratedNotesPerNote: 3
};
var MindStarMapPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    // ============ 防循环相关状态标志 ============
    // 全局防重入锁：防止并发分析
    this.isAnalyzing = false;
    // 忽略列表：插件即将修改的文件路径，修改后自动清理
    this.ignoreNextModify = /* @__PURE__ */ new Set();
    // 分析计数器：记录短时间内笔记被分析的次数，用于熔断
    this.analysisCount = /* @__PURE__ */ new Map();
    // 熔断时间窗口（毫秒）
    this.FUSE_WINDOW_MS = 3e4;
    // 30秒内
    // 熔断阈值
    this.FUSE_THRESHOLD = 3;
    // 启动标志：确保启动时的初始扫描只执行一次
    this.hasPerformedInitialScan = false;
    // ============ 防抖相关 ============
    // 防抖计时器映射：文件路径 -> 计时器ID
    this.debounceTimers = /* @__PURE__ */ new Map();
    // 防抖延迟时间（毫秒）
    this.DEBOUNCE_DELAY_MS = 2e3;
  }
  // 2秒
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_MINDSTARMAP, (leaf) => new MindStarMapView(leaf, this));
    this.addRibbonIcon("dice", "MindStarMap", () => {
      new import_obsidian.Notice("MindStarMap \u5DF2\u542F\u52A8\uFF01\u4F7F\u7528\u547D\u4EE4\u9762\u677F\u6267\u884C AI \u529F\u80FD\u3002");
    });
    this.addCommand({
      id: "ai-organize-current-note",
      name: "AI \u6574\u7406\u5F53\u524D\u7B14\u8BB0",
      callback: () => this.aiOrganizeCurrentNote()
    });
    this.addCommand({
      id: "global-relation-scan",
      name: "\u5168\u5C40\u5173\u7CFB\u626B\u63CF",
      callback: () => this.globalRelationScan()
    });
    this.addCommand({
      id: "full-initialization",
      name: "\u6267\u884C\u5B8C\u6574\u521D\u59CB\u5316",
      callback: () => this.performFullInitialization()
    });
    this.addCommand({
      id: "open-mindstarmap-view",
      name: "\u6253\u5F00\u5173\u8054\u9762\u677F",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "refresh-current-relations",
      name: "\u5237\u65B0\u5F53\u524D\u7B14\u8BB0\u5173\u8054",
      callback: () => this.refreshCurrentNoteRelations()
    });
    this.addCommand({
      id: "generate-related-notes",
      name: "AI \u751F\u6210\u5173\u8054\u7B14\u8BB0",
      callback: () => this.generateRelatedNotesForCurrent()
    });
    this.addSettingTab(new MindStarMapSettingTab(this.app, this));
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => {
      if (file instanceof import_obsidian.TFile) {
        if (file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("AI \u91CD\u65B0\u6574\u7406\u7B14\u8BB0").setIcon("sparkles").onClick(() => {
              this.aiOrganizeNote(file);
            });
          });
          menu.addItem((item) => {
            item.setTitle("AI \u91CD\u65B0\u5EFA\u7ACB\u5173\u7CFB").setIcon("link-2").onClick(() => {
              this.refreshNoteRelations(file);
            });
          });
          menu.addItem((item) => {
            item.setTitle("AI \u751F\u6210\u5173\u8054\u7B14\u8BB0").setIcon("globe").onClick(() => {
              this.generateRelatedNotes(file);
            });
          });
        }
      } else if (file instanceof import_obsidian.TFolder) {
        menu.addItem((item) => {
          item.setTitle("AI \u6279\u91CF\u6574\u7406\u6587\u4EF6\u5939").setIcon("sparkles").onClick(() => {
            this.batchOrganizeFolder(file);
          });
        });
        menu.addItem((item) => {
          item.setTitle("AI \u6279\u91CF\u5EFA\u7ACB\u5173\u7CFB").setIcon("link-2").onClick(() => {
            this.batchScanFolderRelations(file);
          });
        });
      }
    }));
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (this.settings.autoOrganizeOnCreate && file instanceof import_obsidian.TFile && file.extension === "md") {
          this.scheduleAnalysis(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.settings.autoOrganizeOnModify && file instanceof import_obsidian.TFile && file.extension === "md") {
          if (this.ignoreNextModify.has(file.path)) {
            console.log(`[MindStarMap] \u8DF3\u8FC7\u63D2\u4EF6\u81EA\u8EAB\u4FEE\u6539\u7684\u6587\u4EF6: ${file.path}`);
            this.ignoreNextModify.delete(file.path);
            return;
          }
          this.scheduleAnalysis(file);
        }
      })
    );
    if (!this.settings.pluginInitialized) {
      this.settings.pluginInitialized = true;
      await this.saveSettings();
      new import_obsidian.Notice("MindStarMap \u9996\u6B21\u542F\u52A8\uFF0C\u5F00\u59CB\u5B8C\u6574\u521D\u59CB\u5316...");
      setTimeout(() => {
        this.performFullInitialization();
      }, 2e3);
    } else if (this.settings.autoOrganizeOnStartup && !this.hasPerformedInitialScan) {
      this.hasPerformedInitialScan = true;
      new import_obsidian.Notice("MindStarMap \u542F\u52A8\uFF0C\u5F00\u59CB\u81EA\u52A8\u521D\u59CB\u5316...");
      setTimeout(() => {
        this.performFullInitialization();
      }, 2e3);
    }
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_MINDSTARMAP);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async performFullInitialization() {
    if (this.isAnalyzing) {
      new import_obsidian.Notice("MindStarMap: \u6B63\u5728\u6267\u884C\u521D\u59CB\u5316\uFF0C\u8BF7\u7A0D\u5019...");
      return;
    }
    this.isAnalyzing = true;
    new import_obsidian.Notice("MindStarMap: \u5F00\u59CB\u5B8C\u6574\u521D\u59CB\u5316\u6D41\u7A0B...");
    try {
      await this.batchOrganizeAllNotes();
      if (this.settings.autoRelationScanAfterOrganize) {
        new import_obsidian.Notice("MindStarMap: \u6240\u6709\u7B14\u8BB0\u5206\u6790\u5B8C\u6210\uFF0C\u5F00\u59CB\u5173\u7CFB\u626B\u63CF...");
        await this.globalRelationScan(true);
      }
      new import_obsidian.Notice("MindStarMap: \u5B8C\u6574\u521D\u59CB\u5316\u6D41\u7A0B\u5B8C\u6210\uFF01");
    } catch (error) {
      console.error("\u521D\u59CB\u5316\u6D41\u7A0B\u5931\u8D25:", error);
      new import_obsidian.Notice("MindStarMap: \u521D\u59CB\u5316\u6D41\u7A0B\u53D1\u751F\u9519\u8BEF\uFF0C\u8BF7\u68C0\u67E5\u63A7\u5236\u53F0");
    } finally {
      this.isAnalyzing = false;
    }
  }
  async batchOrganizeAllNotes() {
    const files = this.app.vault.getMarkdownFiles();
    const filteredFiles = files.filter((f) => {
      const path = f.path;
      return !this.settings.excludeFolders.some((folder) => path.startsWith(folder));
    });
    const total = filteredFiles.length;
    new import_obsidian.Notice(`MindStarMap: \u5171 ${total} \u7BC7\u7B14\u8BB0\u5F85\u5206\u6790...`);
    const batchSize = this.settings.batchSize;
    let processedCount = 0;
    let successCount = 0;
    for (let i = 0; i < filteredFiles.length; i += batchSize) {
      const batch = filteredFiles.slice(i, i + batchSize);
      const promises = batch.map(async (file) => {
        try {
          await this.aiOrganizeNote(file, false);
          return true;
        } catch (error) {
          console.error(`\u5206\u6790\u7B14\u8BB0 ${file.path} \u5931\u8D25:`, error);
          return false;
        }
      });
      const results = await Promise.all(promises);
      successCount += results.filter((r) => r).length;
      processedCount += batch.length;
      const progress = Math.round(processedCount / total * 100);
      new import_obsidian.Notice(`MindStarMap: \u5206\u6790\u8FDB\u5EA6 ${processedCount}/${total} (${progress}%)`);
    }
    new import_obsidian.Notice(`MindStarMap: \u7B14\u8BB0\u5206\u6790\u5B8C\u6210\uFF0C\u6210\u529F ${successCount}/${total} \u7BC7`);
  }
  async batchOrganizeFolder(folder) {
    const folderPath = folder.path;
    const files = this.app.vault.getMarkdownFiles().filter(
      (f) => f.path.startsWith(folderPath) && !this.settings.excludeFolders.some((exclude) => f.path.startsWith(exclude))
    );
    const total = files.length;
    if (total === 0) {
      new import_obsidian.Notice("MindStarMap: \u6587\u4EF6\u5939\u4E2D\u6CA1\u6709\u7B14\u8BB0");
      return;
    }
    new import_obsidian.Notice(`MindStarMap: \u5171 ${total} \u7BC7\u7B14\u8BB0\u5F85\u5206\u6790...`);
    const batchSize = this.settings.batchSize;
    let processedCount = 0;
    let successCount = 0;
    for (let i = 0; i < files.length; i += batchSize) {
      const batch = files.slice(i, i + batchSize);
      const promises = batch.map(async (file) => {
        try {
          await this.aiOrganizeNote(file, false);
          return true;
        } catch (error) {
          console.error(`\u5206\u6790\u7B14\u8BB0 ${file.path} \u5931\u8D25:`, error);
          return false;
        }
      });
      const results = await Promise.all(promises);
      successCount += results.filter((r) => r).length;
      processedCount += batch.length;
      const progress = Math.round(processedCount / total * 100);
      new import_obsidian.Notice(`MindStarMap: \u5206\u6790\u8FDB\u5EA6 ${processedCount}/${total} (${progress}%)`);
    }
    new import_obsidian.Notice(`MindStarMap: \u7B14\u8BB0\u5206\u6790\u5B8C\u6210\uFF0C\u6210\u529F ${successCount}/${total} \u7BC7`);
  }
  async refreshNoteRelations(file) {
    var _a, _b;
    new import_obsidian.Notice(`MindStarMap: \u6B63\u5728\u4E3A ${file.basename} \u91CD\u65B0\u5EFA\u7ACB\u5173\u7CFB...`);
    try {
      const content = await this.app.vault.read(file);
      const files = this.app.vault.getMarkdownFiles().filter(
        (f) => f.path !== file.path && !this.settings.excludeFolders.some((folder) => f.path.startsWith(folder))
      );
      const sourceCache = this.app.metadataCache.getFileCache(file);
      const sourceTags = ((_a = sourceCache == null ? void 0 : sourceCache.frontmatter) == null ? void 0 : _a.tags) || [];
      const sourceTagsArray = Array.isArray(sourceTags) ? sourceTags : sourceTags ? [sourceTags] : [];
      const relations = [];
      for (const targetFile of files.slice(0, 20)) {
        const targetContent = await this.app.vault.read(targetFile);
        const targetCache = this.app.metadataCache.getFileCache(targetFile);
        const targetTags = ((_b = targetCache == null ? void 0 : targetCache.frontmatter) == null ? void 0 : _b.tags) || [];
        const targetTagsArray = Array.isArray(targetTags) ? targetTags : targetTags ? [targetTags] : [];
        try {
          const result = await this.analyzeRelation(
            file.path,
            file.basename,
            content.substring(0, 500),
            sourceTagsArray,
            targetFile.path,
            targetFile.basename,
            targetContent.substring(0, 500),
            targetTagsArray
          );
          if (result && result.length > 0) {
            relations.push({
              notePath: targetFile.path,
              noteTitle: targetFile.basename,
              relationType: result[0].type,
              commonGround: result[0].commonGround
            });
          }
        } catch (error) {
          console.error("\u5173\u7CFB\u5206\u6790\u5931\u8D25:", error);
        }
      }
      const newContent = this.updateRelationsSection(content, relations);
      await this.app.vault.modify(file, newContent);
      new import_obsidian.Notice(`MindStarMap: ${file.basename} \u5173\u7CFB\u66F4\u65B0\u5B8C\u6210\uFF01`);
    } catch (error) {
      console.error("\u5173\u7CFB\u66F4\u65B0\u5931\u8D25:", error);
      new import_obsidian.Notice("MindStarMap: \u5173\u7CFB\u66F4\u65B0\u5931\u8D25");
    }
  }
  async batchScanFolderRelations(folder) {
    var _a;
    const folderPath = folder.path;
    const files = this.app.vault.getMarkdownFiles().filter(
      (f) => f.path.startsWith(folderPath) && !this.settings.excludeFolders.some((exclude) => f.path.startsWith(exclude))
    );
    const total = files.length;
    if (total === 0) {
      new import_obsidian.Notice("MindStarMap: \u6587\u4EF6\u5939\u4E2D\u6CA1\u6709\u7B14\u8BB0");
      return;
    }
    new import_obsidian.Notice(`MindStarMap: \u6B63\u5728\u4E3A ${total} \u7BC7\u7B14\u8BB0\u5EFA\u7ACB\u5173\u7CFB...`);
    const noteContents = /* @__PURE__ */ new Map();
    const noteTitles = /* @__PURE__ */ new Map();
    const noteTags = /* @__PURE__ */ new Map();
    for (const file of files) {
      const content = await this.app.vault.read(file);
      noteContents.set(file.path, content.substring(0, 500));
      noteTitles.set(file.path, file.basename);
      const cache = this.app.metadataCache.getFileCache(file);
      const tags = ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags) || [];
      const tagsArray = Array.isArray(tags) ? tags : tags ? [tags] : [];
      noteTags.set(file.path, tagsArray);
    }
    const allRelations = [];
    const batchSize = 3;
    let processedCount = 0;
    for (let i = 0; i < files.length; i += batchSize) {
      const batch = files.slice(i, i + batchSize);
      for (const sourceFile of batch) {
        for (const targetFile of files) {
          if (sourceFile.path === targetFile.path)
            continue;
          const sourceContent = noteContents.get(sourceFile.path) || "";
          const targetContent = noteContents.get(targetFile.path) || "";
          const sourceTags = noteTags.get(sourceFile.path) || [];
          const targetTags = noteTags.get(targetFile.path) || [];
          try {
            const relations = await this.analyzeRelation(
              sourceFile.path,
              noteTitles.get(sourceFile.path) || "",
              sourceContent,
              sourceTags,
              targetFile.path,
              noteTitles.get(targetFile.path) || "",
              targetContent,
              targetTags
            );
            if (relations) {
              allRelations.push(...relations);
            }
          } catch (error) {
            console.error("\u5173\u7CFB\u5206\u6790\u5931\u8D25:", error);
          }
          processedCount++;
          if (processedCount % 10 === 0) {
            new import_obsidian.Notice(`MindStarMap: \u5173\u7CFB\u5206\u6790\u8FDB\u5EA6 ${processedCount}`);
          }
        }
      }
    }
    await this.applyRelations(allRelations, noteTitles);
    new import_obsidian.Notice("MindStarMap: \u6587\u4EF6\u5939\u5173\u7CFB\u5EFA\u7ACB\u5B8C\u6210\uFF01");
  }
  // ============ 防抖调度方法 ============
  // 用户停止编辑并保存后，经过防抖延迟才触发分析
  scheduleAnalysis(file) {
    const filePath = file.path;
    const existingTimer = this.debounceTimers.get(filePath);
    if (existingTimer) {
      clearTimeout(existingTimer);
    }
    const newTimer = setTimeout(async () => {
      await this.handleNoteCreateOrModify(file);
      this.debounceTimers.delete(filePath);
    }, this.DEBOUNCE_DELAY_MS);
    this.debounceTimers.set(filePath, newTimer);
    console.log(`[MindStarMap] \u5DF2\u8C03\u5EA6\u5206\u6790: ${file.basename}\uFF08${this.DEBOUNCE_DELAY_MS}ms \u540E\u6267\u884C\uFF09`);
  }
  // ============ 新笔记单次对比（一对一分析）===========
  // 当用户创建或修改笔记时触发，与库中其他笔记逐一对比
  async handleNoteCreateOrModify(file) {
    var _a;
    if (this.isAnalyzing) {
      console.log(`[MindStarMap] \u8DF3\u8FC7\u5206\u6790\uFF08\u5DF2\u6709\u5206\u6790\u6B63\u5728\u8FDB\u884C\uFF09: ${file.path}`);
      return;
    }
    try {
      const content = await this.app.vault.read(file);
      if (!content.trim()) {
        return;
      }
      const cache = this.app.metadataCache.getFileCache(file);
      if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a["auto-generated-related"]) {
        console.log(`[MindStarMap] \u8DF3\u8FC7\u81EA\u52A8\u751F\u6210\u7684\u7B14\u8BB0: ${file.path}`);
        return;
      }
      const now = Date.now();
      const existingRecord = this.analysisCount.get(file.path);
      if (existingRecord) {
        if (now - existingRecord.lastTime < this.FUSE_WINDOW_MS) {
          existingRecord.count++;
          if (existingRecord.count > this.FUSE_THRESHOLD) {
            console.log(`[MindStarMap] \u7194\u65AD\u89E6\u53D1\uFF1A\u7B14\u8BB0\u5728\u77ED\u65F6\u95F4\u5185\u88AB\u5206\u6790\u8D85\u8FC7 ${this.FUSE_THRESHOLD} \u6B21: ${file.path}`);
            new import_obsidian.Notice(`MindStarMap: \u68C0\u6D4B\u5230\u9891\u7E41\u5206\u6790\uFF0C\u5DF2\u8DF3\u8FC7 "${file.basename}"\uFF0C\u8BF7\u68C0\u67E5\u5185\u5BB9\u6216\u624B\u52A8\u5206\u6790`);
            return;
          }
        } else {
          existingRecord.count = 1;
        }
        existingRecord.lastTime = now;
      } else {
        this.analysisCount.set(file.path, { count: 1, lastTime: now });
      }
      this.isAnalyzing = true;
      try {
        new import_obsidian.Notice(`MindStarMap: \u5206\u6790\u7B14\u8BB0: ${file.basename}`);
        await this.aiOrganizeNote(file, false);
        if (this.settings.autoRelationScanAfterOrganize) {
          await this.analyzeAndLinkNote(file, content);
        }
        new import_obsidian.Notice(`MindStarMap: \u7B14\u8BB0\u5206\u6790\u5B8C\u6210: ${file.basename}`);
      } finally {
        this.isAnalyzing = false;
      }
    } catch (error) {
      console.error("\u81EA\u52A8\u5206\u6790\u7B14\u8BB0\u5931\u8D25:", error);
      this.isAnalyzing = false;
    }
  }
  // ============ 新笔记与已有笔记的一对一关联分析 ============
  // 将新笔记与库中所有其他笔记逐一对比，必须同时满足标签重合和语义关联才能建立链接
  async analyzeAndLinkNote(sourceFile, sourceContent) {
    var _a, _b;
    const files = this.app.vault.getMarkdownFiles();
    const filteredFiles = files.filter((f) => {
      const path = f.path;
      return f.path !== sourceFile.path && !this.settings.excludeFolders.some((folder) => path.startsWith(folder));
    });
    if (filteredFiles.length === 0) {
      return;
    }
    const sourceTitle = sourceFile.basename.replace(".md", "");
    const noteTitles = /* @__PURE__ */ new Map();
    const noteTags = /* @__PURE__ */ new Map();
    for (const file of filteredFiles) {
      noteTitles.set(file.path, file.basename.replace(".md", ""));
      const cache = this.app.metadataCache.getFileCache(file);
      const tags = ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags) || [];
      const tagsArray = Array.isArray(tags) ? tags : tags ? [tags] : [];
      noteTags.set(file.path, tagsArray);
    }
    const sourceCache = this.app.metadataCache.getFileCache(sourceFile);
    const sourceTags = ((_b = sourceCache == null ? void 0 : sourceCache.frontmatter) == null ? void 0 : _b.tags) || [];
    const sourceTagsArray = Array.isArray(sourceTags) ? sourceTags : sourceTags ? [sourceTags] : [];
    const relations = [];
    for (const targetFile of filteredFiles) {
      const targetContent = await this.app.vault.read(targetFile);
      const targetTitle = noteTitles.get(targetFile.path) || "";
      const targetTags = noteTags.get(targetFile.path) || [];
      const commonTags = sourceTagsArray.filter(
        (tag) => targetTags.some(
          (targetTag) => tag.toLowerCase() === targetTag.toLowerCase() || targetTag.toLowerCase().includes(tag.toLowerCase()) || tag.toLowerCase().includes(targetTag.toLowerCase())
        )
      );
      if (commonTags.length === 0) {
        console.log(`[MindStarMap] \u8DF3\u8FC7 "${sourceTitle}" \u4E0E "${targetTitle}"\uFF1A\u65E0\u6807\u7B7E\u91CD\u5408`);
        continue;
      }
      try {
        const result = await this.analyzeRelation(
          sourceFile.path,
          sourceTitle,
          sourceContent.substring(0, 500),
          sourceTagsArray,
          // 传入源笔记标签
          targetFile.path,
          targetTitle,
          targetContent.substring(0, 500),
          targetTags
          // 传入目标笔记标签
        );
        if (result && result.length > 0) {
          relations.push(...result);
        }
      } catch (error) {
        console.error("\u5206\u6790\u5173\u7CFB\u5931\u8D25:", error);
      }
    }
    if (relations.length === 0) {
      console.log(`[MindStarMap] \u65B0\u7B14\u8BB0 "${sourceTitle}" \u672A\u627E\u5230\u7B26\u5408\u6761\u4EF6\u7684\u5173\u8054\uFF08\u6807\u7B7E+\u8BED\u4E49\u53CC\u91CD\u5339\u914D\uFF09`);
      return;
    }
    await this.applyRelations(relations, noteTitles);
    console.log(`[MindStarMap] \u4E3A "${sourceTitle}" \u5EFA\u7ACB\u4E86 ${relations.length} \u6761\u5173\u8054\uFF08\u5747\u6EE1\u8DB3\u6807\u7B7E+\u8BED\u4E49\u53CC\u91CD\u6761\u4EF6\uFF09`);
  }
  async aiOrganizeNote(file, showNotice = true) {
    if (showNotice) {
      new import_obsidian.Notice(`MindStarMap: \u6B63\u5728\u5206\u6790 ${file.basename}...`);
    }
    try {
      const content = await this.app.vault.read(file);
      const aiResponse = await this.callAIForOrganization(content);
      if (!aiResponse) {
        if (showNotice) {
          new import_obsidian.Notice(`MindStarMap: AI \u5206\u6790 ${file.basename} \u5931\u8D25`);
        }
        return;
      }
      await this.applyAIResponse(file, content, aiResponse);
      if (showNotice) {
        new import_obsidian.Notice(`MindStarMap: ${file.basename} \u6574\u7406\u5B8C\u6210\uFF01`);
      }
    } catch (error) {
      console.error(`\u5206\u6790\u7B14\u8BB0 ${file.path} \u5931\u8D25:`, error);
      if (showNotice) {
        new import_obsidian.Notice(`MindStarMap: \u5206\u6790 ${file.basename} \u65F6\u53D1\u751F\u9519\u8BEF`);
      }
    }
  }
  async activateView() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_MINDSTARMAP);
    await this.app.workspace.getRightLeaf(false).setViewState({
      type: VIEW_TYPE_MINDSTARMAP,
      active: true
    });
    this.app.workspace.revealLeaf(this.app.workspace.getLeavesOfType(VIEW_TYPE_MINDSTARMAP)[0]);
  }
  async aiOrganizeCurrentNote() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView) {
      new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u7B14\u8BB0");
      return;
    }
    const file = activeView.file;
    if (!file) {
      new import_obsidian.Notice("\u65E0\u6CD5\u83B7\u53D6\u5F53\u524D\u6587\u4EF6");
      return;
    }
    await this.aiOrganizeNote(file);
  }
  async callAIForOrganization(content) {
    const prompt = `\u8BF7\u4ECE\u4EE5\u4E0B\u7B14\u8BB0\u5185\u5BB9\u4E2D\u63D0\u53D6 3-5 \u4E2A\u6700\u6838\u5FC3\u7684\u5173\u952E\u8BCD\u4F5C\u4E3A\u6807\u7B7E\u3002
        
\u8981\u6C42\uFF1A
1. \u6807\u7B7E\u5FC5\u987B\u76F4\u63A5\u53CD\u6620\u6587\u672C\u7684\u8BED\u4E49\u4E3B\u9898\uFF1B
2. \u6807\u7B7E\u5FC5\u987B\u662F\u6587\u4E2D\u51FA\u73B0\u8FC7\u7684\u7279\u5F81\u8BCD\u6216\u7D27\u5BC6\u540C\u4E49\u8BCD\uFF1B
3. \u7981\u6B62\u6DFB\u52A0\u6587\u4E2D\u672A\u63D0\u53CA\u7684\u6CDB\u5316\u6982\u5FF5\u6216\u63A8\u6D4B\u6027\u6807\u7B7E\uFF1B
4. \u6807\u7B7E\u6570\u91CF\u9650\u5236\u5728 3-5 \u4E2A\uFF0C\u907F\u514D\u8FC7\u5EA6\u6807\u6CE8\uFF1B
5. \u8FD4\u56DE\u683C\u5F0F\u4E3A JSON\uFF0C\u793A\u4F8B\uFF1A{"tags": ["\u6807\u7B7E1", "\u6807\u7B7E2", "\u6807\u7B7E3"]}

\u7B14\u8BB0\u5185\u5BB9\uFF1A
${content.substring(0, 2e3)}

\u8BF7\u53EA\u8FD4\u56DE JSON\uFF0C\u4E0D\u8981\u6DFB\u52A0\u5176\u4ED6\u5185\u5BB9\u3002`;
    try {
      const response = await this.makeAIRequest(prompt);
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const result = JSON.parse(jsonMatch[0]);
        const filteredTags = (result.tags || []).slice(0, 5);
        return { tags: filteredTags };
      }
      return null;
    } catch (error) {
      console.error("AI request failed:", error);
      return null;
    }
  }
  async applyAIResponse(file, content, response) {
    var _a;
    let newContent = content;
    const frontmatter = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const tagsToAdd = response.tags || [];
    if (tagsToAdd.length > 0) {
      if (frontmatter) {
        const existingTags = frontmatter.tags || [];
        const mergedTags = [.../* @__PURE__ */ new Set([...existingTags, ...tagsToAdd])];
        newContent = this.updateFrontmatterTags(newContent, mergedTags);
      } else {
        newContent = this.addFrontmatter(newContent, { tags: tagsToAdd });
      }
    }
    if (newContent !== content) {
      this.ignoreNextModify.add(file.path);
      await this.app.vault.modify(file, newContent);
    }
  }
  async generateRelatedNotesForCurrent() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView || !activeView.file) {
      new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u7B14\u8BB0");
      return;
    }
    await this.generateRelatedNotes(activeView.file);
  }
  async generateRelatedNotes(file) {
    if (!this.settings.enableWebSearch) {
      new import_obsidian.Notice("MindStarMap: \u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u542F\u7528 AI \u8054\u7F51\u641C\u7D22\u529F\u80FD");
      return;
    }
    if (this.settings.provider !== "deepseek") {
      new import_obsidian.Notice("MindStarMap: \u4EC5 DeepSeek \u652F\u6301\u8054\u7F51\u641C\u7D22\u529F\u80FD");
      return;
    }
    if (!this.settings.apiKey) {
      new import_obsidian.Notice("MindStarMap: \u8BF7\u5148\u914D\u7F6E DeepSeek API Key");
      return;
    }
    new import_obsidian.Notice(`MindStarMap: \u6B63\u5728\u4E3A ${file.basename} \u751F\u6210\u5173\u8054\u7B14\u8BB0...`);
    try {
      const content = await this.app.vault.read(file);
      const title = file.basename.replace(".md", "");
      const existingGeneratedNotes = this.getGeneratedNotesForFile(file);
      if (existingGeneratedNotes >= this.settings.maxGeneratedNotesPerNote) {
        new import_obsidian.Notice(`MindStarMap: \u5DF2\u8FBE\u5230\u6700\u5927\u751F\u6210\u7B14\u8BB0\u6570\uFF08${this.settings.maxGeneratedNotesPerNote}\uFF09`);
        return;
      }
      const prompt = `\u8BF7\u641C\u7D22\u4E0E "${title}" \u76F8\u5173\u7684\u6743\u5A01\u4FE1\u606F\uFF0C\u5305\u62EC\u6700\u65B0\u8D44\u8BAF\u3001\u5B66\u672F\u8D44\u6599\u3001\u6280\u672F\u6587\u6863\u7B49\u3002\u8BF7\u8FD4\u56DE\u7ED3\u6784\u5316\u7684\u641C\u7D22\u7ED3\u679C\uFF0C\u5305\u542B\u6807\u9898\u3001\u6458\u8981\u548C\u6765\u6E90\u94FE\u63A5\u3002`;
      const searchResponse = await this.makeAIRequest(prompt, true);
      const searchResults = this.parseDeepSeekSearchResults(searchResponse);
      if (!searchResults || searchResults.length === 0) {
        new import_obsidian.Notice("MindStarMap: \u672A\u627E\u5230\u76F8\u5173\u641C\u7D22\u7ED3\u679C");
        return;
      }
      const numToGenerate = this.settings.maxGeneratedNotesPerNote - existingGeneratedNotes;
      for (let i = 0; i < Math.min(numToGenerate, searchResults.length); i++) {
        const result = searchResults[i];
        await this.createRelatedNote(file, result, i + 1);
      }
      new import_obsidian.Notice(`MindStarMap: \u6210\u529F\u751F\u6210 ${Math.min(numToGenerate, searchResults.length)} \u7BC7\u5173\u8054\u7B14\u8BB0\uFF01`);
    } catch (error) {
      console.error("\u751F\u6210\u5173\u8054\u7B14\u8BB0\u5931\u8D25:", error);
      new import_obsidian.Notice("MindStarMap: \u751F\u6210\u5173\u8054\u7B14\u8BB0\u65F6\u53D1\u751F\u9519\u8BEF");
    }
  }
  parseDeepSeekSearchResults(response) {
    const results = [];
    try {
      const urlRegex = /https?:\/\/[^\s\)]+/g;
      const urls = response.match(urlRegex) || [];
      const lines = response.split("\n");
      let currentTitle = "";
      let currentSnippet = "";
      for (const line of lines) {
        if (line.match(/^[\d\*\-]+\s*[^\s]/)) {
          if (currentTitle) {
            results.push({
              title: currentTitle.trim(),
              snippet: currentSnippet.trim(),
              url: urls.shift() || "",
              source: urls[urls.length - 1] || ""
            });
          }
          currentTitle = line.replace(/^[\d\*\-]+\s*/, "");
          currentSnippet = "";
        } else if (currentTitle) {
          currentSnippet += line + " ";
        }
      }
      if (currentTitle) {
        results.push({
          title: currentTitle.trim(),
          snippet: currentSnippet.trim(),
          url: urls.shift() || "",
          source: urls[urls.length - 1] || ""
        });
      }
    } catch (error) {
      console.error("\u89E3\u6790\u641C\u7D22\u7ED3\u679C\u5931\u8D25:", error);
    }
    return results.filter((r) => r.title && r.url);
  }
  async createRelatedNote(sourceFile, searchResult, index) {
    var _a, _b, _c;
    const sourceTitle = sourceFile.basename.replace(".md", "");
    const newTitle = `${sourceTitle}-\u5173\u8054${index}`;
    const existingFile = this.app.vault.getAbstractFileByPath(`${((_a = sourceFile.parent) == null ? void 0 : _a.path) || ""}/${newTitle}.md`);
    if (existingFile) {
      return;
    }
    const frontmatter = (_b = this.app.metadataCache.getFileCache(sourceFile)) == null ? void 0 : _b.frontmatter;
    const sourceTags = (frontmatter == null ? void 0 : frontmatter.tags) || [];
    const newTags = [.../* @__PURE__ */ new Set([...sourceTags, "AI\u751F\u6210", "\u5173\u8054\u62D3\u5C55"])];
    const content = await this.generateNoteContent(searchResult);
    const frontmatterContent = `---
title: "${searchResult.title}"
tags: [${newTags.map((t) => `"${t}"`).join(", ")}]
generatedFrom: "${sourceTitle}"
---

## \u6982\u8FF0

${content}

## \u5173\u8054

- [[${sourceTitle}|\u76F8\u5173\u62D3\u5C55]]

## \u53C2\u8003\u8D44\u6599

- [${searchResult.title}](${searchResult.url})
`;
    const filePath = `${((_c = sourceFile.parent) == null ? void 0 : _c.path) || ""}/${newTitle}.md`;
    await this.app.vault.create(filePath, frontmatterContent);
    await this.addRelationToNote(sourceFile, newTitle, "\u76F8\u5173\u62D3\u5C55");
  }
  async generateNoteContent(searchResult) {
    const prompt = `\u57FA\u4E8E\u4EE5\u4E0B\u641C\u7D22\u7ED3\u679C\uFF0C\u64B0\u5199\u4E00\u7BC7\u8BE6\u7EC6\u7684\u7B14\u8BB0\u5185\u5BB9\uFF1A

\u641C\u7D22\u7ED3\u679C\u6807\u9898\uFF1A${searchResult.title}
\u641C\u7D22\u7ED3\u679C\u6458\u8981\uFF1A${searchResult.snippet}
\u6765\u6E90\u94FE\u63A5\uFF1A${searchResult.url}

\u8BF7\u64B0\u5199\u4E00\u7BC7\u5B8C\u6574\u7684\u7B14\u8BB0\u5185\u5BB9\uFF0C\u5305\u62EC\uFF1A
1. \u4E3B\u9898\u6982\u8FF0
2. \u6838\u5FC3\u8981\u70B9
3. \u5173\u952E\u4FE1\u606F

\u8981\u6C42\uFF1A
- \u5185\u5BB9\u5FC5\u987B\u57FA\u4E8E\u641C\u7D22\u7ED3\u679C\uFF0C\u4E0D\u8981\u865A\u6784\u4FE1\u606F
- \u4F7F\u7528 Markdown \u683C\u5F0F
- \u8BED\u8A00\u6E05\u6670\u3001\u7ED3\u6784\u5408\u7406
- \u7BC7\u5E45\u9002\u4E2D\uFF08200-500\u5B57\uFF09

\u8BF7\u53EA\u8FD4\u56DE\u7B14\u8BB0\u5185\u5BB9\uFF0C\u4E0D\u8981\u6DFB\u52A0\u5176\u4ED6\u5185\u5BB9\u3002`;
    try {
      const response = await this.makeAIRequest(prompt);
      return response.trim();
    } catch (error) {
      return searchResult.snippet;
    }
  }
  async addRelationToNote(file, targetTitle, relationType) {
    const content = await this.app.vault.read(file);
    const relations = [{
      notePath: targetTitle,
      noteTitle: targetTitle,
      relationType,
      commonGround: ""
    }];
    const newContent = this.updateRelationsSection(content, relations);
    await this.app.vault.modify(file, newContent);
  }
  updateFrontmatterTags(content, tags) {
    const frontmatterRegex = /^---\n([\s\S]*?)\n---/;
    const match = content.match(frontmatterRegex);
    if (match) {
      let frontmatter = match[1];
      const tagsLine = `tags: [${tags.map((t) => `"${t}"`).join(", ")}]`;
      if (frontmatter.includes("tags:")) {
        frontmatter = frontmatter.replace(/tags:\s*\[[\s\S]*?\]/, tagsLine);
        frontmatter = frontmatter.replace(/tags:\s*\n\s*-[\s\S]*?(?=\n[^-\s]|\n---|$)/, tagsLine);
      } else {
        frontmatter = frontmatter + `
${tagsLine}`;
      }
      return content.replace(frontmatterRegex, `---
${frontmatter}
---`);
    }
    return this.addFrontmatter(content, { tags });
  }
  addFrontmatter(content, data) {
    const frontmatter = Object.entries(data).map(([key, value]) => {
      if (Array.isArray(value)) {
        return `${key}: [${value.map((v) => `"${v}"`).join(", ")}]`;
      }
      return `${key}: "${value}"`;
    }).join("\n");
    return `---
${frontmatter}
---

${content}`;
  }
  // ============ 全局关联分析（仅标签匹配）===========
  // 当用户点击"全局关联分析"按钮时触发，仅根据相同标签建立关联
  async globalRelationScan(isNested = false) {
    var _a;
    if (this.isAnalyzing && !isNested) {
      new import_obsidian.Notice("MindStarMap: \u6B63\u5728\u6267\u884C\u626B\u63CF\uFF0C\u8BF7\u7A0D\u5019...");
      return;
    }
    if (!isNested) {
      this.isAnalyzing = true;
    }
    new import_obsidian.Notice("MindStarMap: \u5F00\u59CB\u5168\u5C40\u6807\u7B7E\u5173\u8054\u5206\u6790...");
    try {
      const files = this.app.vault.getMarkdownFiles();
      const filteredFiles = files.filter((f) => {
        const path = f.path;
        return !this.settings.excludeFolders.some((folder) => path.startsWith(folder));
      });
      const noteTags = /* @__PURE__ */ new Map();
      const noteTitles = /* @__PURE__ */ new Map();
      for (const file of filteredFiles) {
        const cache = this.app.metadataCache.getFileCache(file);
        const tags = ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags) || [];
        const tagsArray = Array.isArray(tags) ? tags : tags ? [tags] : [];
        noteTags.set(file.path, tagsArray);
        noteTitles.set(file.path, file.basename.replace(".md", ""));
      }
      const allRelations = [];
      const processedPairs = /* @__PURE__ */ new Set();
      for (let i = 0; i < filteredFiles.length; i++) {
        for (let j = i + 1; j < filteredFiles.length; j++) {
          const sourceFile = filteredFiles[i];
          const targetFile = filteredFiles[j];
          const pairKey = [sourceFile.path, targetFile.path].sort().join("||");
          if (processedPairs.has(pairKey)) {
            continue;
          }
          processedPairs.add(pairKey);
          const sourceTags = noteTags.get(sourceFile.path) || [];
          const targetTags = noteTags.get(targetFile.path) || [];
          const commonTags = sourceTags.filter((tag) => targetTags.includes(tag));
          if (commonTags.length > 0) {
            const relationType = `\u6807\u7B7E\u5173\u8054`;
            const commonGround = `\u5171\u540C\u6807\u7B7E: ${commonTags.join(", ")}`;
            allRelations.push({
              source: sourceFile.path,
              target: targetFile.path,
              type: relationType,
              commonGround
            });
            allRelations.push({
              source: targetFile.path,
              target: sourceFile.path,
              type: relationType,
              commonGround
            });
          }
        }
      }
      if (allRelations.length > 0) {
        await this.applyRelations(allRelations, noteTitles);
        new import_obsidian.Notice(`MindStarMap: \u5168\u5C40\u6807\u7B7E\u5173\u8054\u5206\u6790\u5B8C\u6210\uFF01\u5171\u5EFA\u7ACB ${allRelations.length / 2} \u5BF9\u5173\u8054`);
      } else {
        new import_obsidian.Notice("MindStarMap: \u5168\u5C40\u6807\u7B7E\u5173\u8054\u5206\u6790\u5B8C\u6210\uFF01\u672A\u627E\u5230\u6709\u5171\u540C\u6807\u7B7E\u7684\u7B14\u8BB0\u5BF9");
      }
    } catch (error) {
      console.error("\u5168\u5C40\u6807\u7B7E\u5173\u8054\u5206\u6790\u5931\u8D25:", error);
      new import_obsidian.Notice("MindStarMap: \u5168\u5C40\u6807\u7B7E\u5173\u8054\u5206\u6790\u53D1\u751F\u9519\u8BEF");
    } finally {
      if (!isNested) {
        this.isAnalyzing = false;
      }
    }
  }
  // ============ 语义关系分析方法 ============
  // 分析两篇笔记之间是否存在语义关联，返回 { hasRelation: boolean, type?: string, commonGround?: string }
  async analyzeRelation(sourcePath, sourceTitle, sourceContent, sourceTags, targetPath, targetTitle, targetContent, targetTags) {
    const commonTags = sourceTags.filter(
      (tag) => targetTags.some((t) => t.toLowerCase() === tag.toLowerCase())
    );
    const prompt = `\u5206\u6790\u4EE5\u4E0B\u4E24\u4E2A\u7B14\u8BB0\u5185\u5BB9\u662F\u5426\u5B58\u5728\u8BED\u4E49\u5173\u8054\u3002

\u7B14\u8BB01: ${sourceTitle}
\u6807\u7B7E: ${sourceTags.join(", ") || "\u65E0"}
\u5185\u5BB9\u7247\u6BB5:
${sourceContent.substring(0, 300)}

\u7B14\u8BB02: ${targetTitle}
\u6807\u7B7E: ${targetTags.join(", ") || "\u65E0"}
\u5185\u5BB9\u7247\u6BB5:
${targetContent.substring(0, 300)}

\u5171\u540C\u6807\u7B7E: ${commonTags.join(", ") || "\u65E0"}

\u8BF7\u5224\u65AD\uFF1A
1. \u4E24\u7BC7\u7B14\u8BB0\u662F\u5426\u5B58\u5728\u660E\u786E\u7684\u8BED\u4E49\u5173\u8054\uFF1F\uFF08\u5982\u8865\u5145\u3001\u76F8\u53CD\u3001\u56E0\u679C\u3001\u793A\u4F8B\u3001\u4E3B\u9898\u5EF6\u7EED\u7B49\uFF09
2. \u5982\u679C\u5B58\u5728\u5173\u8054\uFF0C\u8BF7\u660E\u786E\u8BF4\u660E\u5173\u7CFB\u7C7B\u578B\u548C\u5171\u540C\u5173\u6CE8\u70B9\u3002

\u8FD4\u56DE\u683C\u5F0F\u4E3A JSON\uFF1A
{
    "hasRelation": true/false,
    "type": "\u5173\u7CFB\u7C7B\u578B\uFF08\u5982\uFF1A\u8865\u5145|\u76F8\u53CD|\u56E0\u679C|\u793A\u4F8B|\u76F8\u4F3C|\u5BF9\u6BD4|\u4E3B\u9898\u5EF6\u7EED\uFF09",
    "commonGround": "\u5171\u540C\u5173\u6CE8\u70B9\u6216\u5173\u8054\u7406\u7531\uFF08\u7B80\u77ED\u63CF\u8FF0\uFF09"
}

\u6CE8\u610F\uFF1A
- \u53EA\u6709\u5F53\u5B58\u5728\u660E\u786E\u7684\u8BED\u4E49\u8054\u7CFB\u65F6\uFF0ChasRelation \u624D\u4E3A true
- \u5982\u679C\u5185\u5BB9\u65E0\u5173\u6216\u5173\u8054\u5F88\u5F31\uFF0ChasRelation \u5E94\u4E3A false
- \u4EC5\u5F53 hasRelation \u4E3A true \u65F6\uFF0Ctype \u548C commonGround \u5B57\u6BB5\u624D\u9700\u8981\u586B\u5199
- \u8BF7\u4E25\u683C\u6309\u7167 JSON \u683C\u5F0F\u8FD4\u56DE\uFF0C\u4E0D\u8981\u6DFB\u52A0\u5176\u4ED6\u5185\u5BB9`;
    try {
      const response = await this.makeAIRequest(prompt);
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const result = JSON.parse(jsonMatch[0]);
        if (result.hasRelation) {
          return [{
            source: sourcePath,
            target: targetPath,
            type: result.type || "\u5173\u8054",
            commonGround: result.commonGround || "\u8BED\u4E49\u5173\u8054"
          }];
        } else {
          console.log(`[MindStarMap] AI \u5224\u5B9A "${sourceTitle}" \u4E0E "${targetTitle}" \u65E0\u8BED\u4E49\u5173\u8054`);
          return [];
        }
      }
      return null;
    } catch (error) {
      console.error("\u5206\u6790\u5173\u7CFB\u5931\u8D25:", error);
      return null;
    }
  }
  async applyRelations(relations, noteTitles) {
    const relationMap = /* @__PURE__ */ new Map();
    const maxRelations = this.settings.maxRelationsPerNote || 5;
    for (const relation of relations) {
      const sourceRelations = relationMap.get(relation.source) || [];
      if (sourceRelations.length < maxRelations) {
        sourceRelations.push({
          notePath: relation.target,
          noteTitle: noteTitles.get(relation.target) || relation.target,
          relationType: relation.type,
          commonGround: relation.commonGround
        });
        relationMap.set(relation.source, sourceRelations);
      }
      const targetRelations = relationMap.get(relation.target) || [];
      if (targetRelations.length < maxRelations) {
        targetRelations.push({
          notePath: relation.source,
          noteTitle: noteTitles.get(relation.source) || relation.source,
          relationType: relation.type,
          commonGround: relation.commonGround
        });
        relationMap.set(relation.target, targetRelations);
      }
    }
    for (const [notePath, noteRelations] of relationMap) {
      const file = this.app.vault.getAbstractFileByPath(notePath);
      if (file instanceof import_obsidian.TFile) {
        try {
          const content = await this.app.vault.read(file);
          const newContent = this.updateRelationsSection(content, noteRelations);
          this.ignoreNextModify.add(notePath);
          await this.app.vault.modify(file, newContent);
        } catch (error) {
          console.error("Failed to update file:", error);
        }
      }
    }
  }
  updateRelationsSection(content, relations) {
    const relationsSectionRegex = /## 关联\n([\s\S]*?)(?=\n##|\n---|$)/;
    const maxRelations = this.settings.maxRelationsPerNote || 5;
    const filteredRelations = relations.slice(0, maxRelations);
    const links = filteredRelations.map((r) => `- [[${r.noteTitle}|${r.relationType}]]`).join("\n");
    if (relationsSectionRegex.test(content)) {
      return content.replace(
        relationsSectionRegex,
        `## \u5173\u8054
${links}
`
      );
    } else {
      return content + `

## \u5173\u8054
${links}
`;
    }
  }
  async refreshCurrentNoteRelations() {
    var _a, _b;
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView || !activeView.file) {
      new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u7B14\u8BB0");
      return;
    }
    new import_obsidian.Notice("\u6B63\u5728\u5237\u65B0\u5173\u8054...");
    const file = activeView.file;
    const content = await this.app.vault.read(file);
    const sourceCache = this.app.metadataCache.getFileCache(file);
    const sourceTags = ((_a = sourceCache == null ? void 0 : sourceCache.frontmatter) == null ? void 0 : _a.tags) || [];
    const sourceTagsArray = Array.isArray(sourceTags) ? sourceTags : sourceTags ? [sourceTags] : [];
    const files = this.app.vault.getMarkdownFiles();
    const filteredFiles = files.filter((f) => {
      const path = f.path;
      return !this.settings.excludeFolders.some((folder) => path.startsWith(folder)) && f.path !== file.path;
    });
    const relations = [];
    for (const targetFile of filteredFiles.slice(0, 10)) {
      const targetContent = await this.app.vault.read(targetFile);
      const targetCache = this.app.metadataCache.getFileCache(targetFile);
      const targetTags = ((_b = targetCache == null ? void 0 : targetCache.frontmatter) == null ? void 0 : _b.tags) || [];
      const targetTagsArray = Array.isArray(targetTags) ? targetTags : targetTags ? [targetTags] : [];
      try {
        const result = await this.analyzeRelation(
          file.path,
          file.basename,
          content.substring(0, 500),
          sourceTagsArray,
          targetFile.path,
          targetFile.basename,
          targetContent.substring(0, 500),
          targetTagsArray
        );
        if (result && result.length > 0) {
          relations.push({
            notePath: targetFile.path,
            noteTitle: targetFile.basename,
            relationType: result[0].type,
            commonGround: result[0].commonGround
          });
        }
      } catch (error) {
        console.error("Analysis failed:", error);
      }
    }
    const newContent = this.updateRelationsSection(content, relations);
    await this.app.vault.modify(file, newContent);
    new import_obsidian.Notice("\u5173\u8054\u5237\u65B0\u5B8C\u6210\uFF01");
    this.activateView();
  }
  async makeAIRequest(prompt, enableSearch = false) {
    const { provider, apiKey, endpointUrl, modelName, temperature, maxTokens } = this.settings;
    let url = "";
    let headers = {};
    let body = {};
    switch (provider) {
      case "deepseek":
        let deepseekBaseUrl = endpointUrl || "https://api.deepseek.com";
        if (!deepseekBaseUrl.endsWith("/v1/chat/completions")) {
          url = `${deepseekBaseUrl}/v1/chat/completions`;
        } else {
          url = deepseekBaseUrl;
        }
        headers = {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        };
        body = {
          model: modelName || "deepseek-v4-flash",
          messages: [{ role: "user", content: prompt }],
          temperature,
          max_tokens: maxTokens
        };
        if (enableSearch) {
          body.search = true;
        }
        break;
      case "openai":
        let baseUrl = endpointUrl || "https://api.openai.com";
        if (!baseUrl.endsWith("/v1/chat/completions")) {
          url = `${baseUrl}/v1/chat/completions`;
        } else {
          url = baseUrl;
        }
        headers = {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        };
        body = {
          model: modelName || "gpt-3.5-turbo",
          messages: [{ role: "user", content: prompt }],
          temperature,
          max_tokens: maxTokens
        };
        break;
      case "ollama":
        url = endpointUrl || "http://localhost:11434/api/generate";
        headers = { "Content-Type": "application/json" };
        body = {
          model: modelName || "llama2",
          prompt,
          stream: false
        };
        break;
      case "xinghuo":
        url = endpointUrl || "https://spark-api-open.xf-yun.com/v1/chat/completions";
        headers = {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        };
        body = {
          model: modelName || "generalv3.5",
          messages: [{ role: "user", content: prompt }],
          temperature,
          max_tokens: maxTokens
        };
        break;
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "POST",
        headers,
        body: JSON.stringify(body)
      });
      if (provider === "ollama") {
        return response.json.response;
      }
      return response.json.choices[0].message.content;
    } catch (error) {
      console.error(`MindStarMap AI Request Error:`);
      console.error(`Provider: ${provider}`);
      console.error(`URL: ${url}`);
      console.error(`Error:`, error);
      if (error.message) {
        console.error(`Error Message: ${error.message}`);
      }
      if (error.body) {
        console.error(`Response Body: ${error.body}`);
      }
      throw error;
    }
  }
  async testConnection() {
    try {
      console.log("MindStarMap: Testing connection...");
      console.log("Provider:", this.settings.provider);
      console.log("Endpoint:", this.settings.endpointUrl || "default");
      console.log("Model:", this.settings.modelName || "default");
      const response = await this.makeAIRequest('Hello, respond with "OK"');
      const success = response.includes("OK") || response.length > 0;
      console.log("MindStarMap: Connection test result:", success);
      console.log("Response:", response);
      return { success };
    } catch (error) {
      console.error("MindStarMap Connection Test Failed:", error);
      let errorMessage = "\u8FDE\u63A5\u5931\u8D25";
      if (error.message) {
        errorMessage = error.message;
      } else if (error.status) {
        errorMessage = `HTTP ${error.status}: ${error.statusText || "\u672A\u77E5\u9519\u8BEF"}`;
      }
      return { success: false, error: errorMessage };
    }
  }
  getCurrentNoteRelations() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView || !activeView.file)
      return [];
    const file = activeView.file;
    return this.extractRelationsSection(file);
  }
  extractRelationsSection(file) {
    const content = this.app.vault.cachedRead(file);
    const relationsSectionRegex = /## 关联\n([\s\S]*?)(?=\n##|\n---|$)/;
    const match = content.match(relationsSectionRegex);
    if (!match)
      return [];
    const relations = [];
    const lines = match[1].split("\n");
    for (const line of lines) {
      const linkMatch = line.match(/\[\[([^\]]+)\]\]/);
      if (linkMatch) {
        const parts = linkMatch[1].split("|");
        const noteTitle = parts[0];
        const relationInfo = parts[1] || "";
        const typeMatch = relationInfo.match(/关系：([^\(]+)/);
        const commonGroundMatch = relationInfo.match(/\(([^\)]+)\)/);
        relations.push({
          notePath: noteTitle,
          noteTitle,
          relationType: typeMatch ? typeMatch[1].trim() : "related",
          commonGround: commonGroundMatch ? commonGroundMatch[1].trim() : ""
        });
      }
    }
    return relations;
  }
};
var MindStarMapView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_MINDSTARMAP;
  }
  getDisplayText() {
    return "MindStarMap \u5173\u8054";
  }
  getIcon() {
    return "dice";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("mindstarmap-view");
    this.renderView();
  }
  async onClose() {
    this.containerEl.children[1].empty();
  }
  renderView() {
    const container = this.containerEl.children[1];
    container.empty();
    const header = container.createDiv({ cls: "mindstarmap-header" });
    header.createEl("h3", { text: "\u5173\u8054\u60F3\u6CD5" });
    header.createEl("button", { cls: "mindstarmap-refresh-btn", text: "\u5237\u65B0" }).addEventListener("click", () => {
      this.plugin.refreshCurrentNoteRelations();
    });
    const relations = this.plugin.getCurrentNoteRelations();
    if (relations.length === 0) {
      const emptyState = container.createDiv({ cls: "mindstarmap-empty" });
      emptyState.createEl("p", { text: "\u6682\u65E0\u5173\u8054" });
      emptyState.createEl("p", { cls: "hint", text: '\u6267\u884C"\u5168\u5C40\u5173\u7CFB\u626B\u63CF"\u6216"\u5237\u65B0\u5F53\u524D\u7B14\u8BB0\u5173\u8054"\u6765\u53D1\u73B0\u5173\u8054' });
      return;
    }
    const list = container.createDiv({ cls: "mindstarmap-list" });
    for (const relation of relations) {
      const item = list.createDiv({ cls: "mindstarmap-item" });
      const titleEl = item.createEl("a", { cls: "mindstarmap-title", text: relation.noteTitle });
      titleEl.addEventListener("click", () => {
        this.app.workspace.openLinkText(relation.noteTitle, "", false);
      });
      const metaEl = item.createDiv({ cls: "mindstarmap-meta" });
      metaEl.createEl("span", { cls: "mindstarmap-type", text: relation.relationType });
      if (relation.commonGround) {
        metaEl.createEl("span", { cls: "mindstarmap-common", text: `(${relation.commonGround})` });
      }
    }
  }
};
var MindStarMapSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "MindStarMap \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("AI \u4F9B\u5E94\u5546").setDesc("\u9009\u62E9 AI \u670D\u52A1\u4F9B\u5E94\u5546").addDropdown((dropdown) => dropdown.addOption("deepseek", "DeepSeek").addOption("openai", "OpenAI \u517C\u5BB9").addOption("ollama", "Ollama (\u672C\u5730)").addOption("xinghuo", "\u8BAF\u98DE\u661F\u706B").setValue(this.plugin.settings.provider).onChange(async (value) => {
      this.plugin.settings.provider = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.provider === "xinghuo") {
      new import_obsidian.Setting(containerEl).setName("APP ID").addText((text) => text.setPlaceholder("\u8F93\u5165 APP ID").setValue(this.plugin.settings.appId).onChange(async (value) => {
        this.plugin.settings.appId = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("API Secret").addText((text) => text.setPlaceholder("\u8F93\u5165 API Secret").setValue(this.plugin.settings.apiSecret).onChange(async (value) => {
        this.plugin.settings.apiSecret = value;
        await this.plugin.saveSettings();
      }));
    }
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u8F93\u5165 API Key").addText((text) => {
      text.setPlaceholder("\u8F93\u5165 API Key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.style.width = "100%";
    });
    if (this.plugin.settings.provider !== "ollama") {
      new import_obsidian.Setting(containerEl).setName("Endpoint URL").setDesc("\u81EA\u5B9A\u4E49 API \u7AEF\u70B9\uFF08\u53EF\u9009\uFF09").addText((text) => {
        text.setPlaceholder("https://api.example.com/v1/chat/completions").setValue(this.plugin.settings.endpointUrl).onChange(async (value) => {
          this.plugin.settings.endpointUrl = value;
          await this.plugin.saveSettings();
        });
        text.inputEl.style.width = "100%";
      });
    } else {
      new import_obsidian.Setting(containerEl).setName("Ollama \u5730\u5740").setDesc("\u672C\u5730 Ollama \u670D\u52A1\u5730\u5740").addText((text) => {
        text.setPlaceholder("http://localhost:11434").setValue(this.plugin.settings.endpointUrl).onChange(async (value) => {
          this.plugin.settings.endpointUrl = value;
          await this.plugin.saveSettings();
        });
        text.inputEl.style.width = "100%";
      });
    }
    new import_obsidian.Setting(containerEl).setName("\u6A21\u578B\u540D\u79F0").setDesc("\u6307\u5B9A\u4F7F\u7528\u7684\u6A21\u578B").addText((text) => {
      text.setPlaceholder("deepseek-chat / gpt-3.5-turbo / llama2").setValue(this.plugin.settings.modelName).onChange(async (value) => {
        this.plugin.settings.modelName = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.style.width = "100%";
    });
    new import_obsidian.Setting(containerEl).setName("Temperature").setDesc(`\u5F53\u524D\u503C: ${this.plugin.settings.temperature}`).addSlider((slider) => slider.setLimits(0, 1, 0.1).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.temperature = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName("Max Tokens").setDesc(`\u5F53\u524D\u503C: ${this.plugin.settings.maxTokens}`).addSlider((slider) => slider.setLimits(256, 4096, 128).setValue(this.plugin.settings.maxTokens).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxTokens = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6D4B\u8BD5\u8FDE\u63A5").setDesc("\u9A8C\u8BC1 API \u914D\u7F6E\u662F\u5426\u6B63\u786E").addButton((button) => button.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5").onClick(async () => {
      button.setButtonText("\u6D4B\u8BD5\u4E2D...");
      button.setDisabled(true);
      const result = await this.plugin.testConnection();
      button.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5");
      button.setDisabled(false);
      if (result.success) {
        new import_obsidian.Notice("\u8FDE\u63A5\u6210\u529F\uFF01");
      } else {
        const errorMsg = result.error || "\u8FDE\u63A5\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u914D\u7F6E";
        new import_obsidian.Notice(`\u8FDE\u63A5\u5931\u8D25: ${errorMsg}`, 5e3);
      }
    }));
    containerEl.createEl("h3", { text: "\u5173\u8054\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u6BCF\u7B14\u8BB0\u6700\u5927\u5173\u8054\u6570").setDesc(`\u5F53\u524D\u503C: ${this.plugin.settings.maxRelationsPerNote}\uFF08\u8303\u56F4\uFF1A1-99999\uFF09`).addSlider((slider) => slider.setLimits(1, 99999, 1).setValue(this.plugin.settings.maxRelationsPerNote).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxRelationsPerNote = value;
      await this.plugin.saveSettings();
      this.display();
    })).addText((text) => text.setPlaceholder("\u8F93\u5165\u6570\u5B57").setValue(this.plugin.settings.maxRelationsPerNote.toString()).onChange(async (value) => {
      const num = parseInt(value, 10);
      if (!isNaN(num) && num >= 1 && num <= 99999) {
        this.plugin.settings.maxRelationsPerNote = num;
        await this.plugin.saveSettings();
        this.display();
      } else {
        text.setValue(this.plugin.settings.maxRelationsPerNote.toString());
      }
    }).inputEl.style.width = "80px");
    containerEl.createEl("h3", { text: "AI \u8054\u7F51\u641C\u7D22\u8BBE\u7F6E" });
    if (this.plugin.settings.provider === "deepseek") {
      containerEl.createEl("div", {
        text: "\u2705 \u5DF2\u542F\u7528\u8054\u7F51\u641C\u7D22\uFF08\u901A\u8FC7 DeepSeek API \u83B7\u53D6\u5B9E\u65F6\u7F51\u7EDC\u4FE1\u606F\uFF09",
        cls: "setting-item-description"
      });
    }
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528 AI \u8054\u7F51\u521B\u5EFA\u5173\u8054\u7B14\u8BB0").setDesc("\u542F\u7528\u540E\uFF0CAI \u5C06\u901A\u8FC7\u4E92\u8054\u7F51\u641C\u7D22\u751F\u6210\u5173\u8054\u7B14\u8BB0").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableWebSearch).onChange(async (value) => {
      this.plugin.settings.enableWebSearch = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6BCF\u7BC7\u7B14\u8BB0\u6700\u5927\u751F\u6210\u7B14\u8BB0\u6570").setDesc(`\u5F53\u524D\u503C: ${this.plugin.settings.maxGeneratedNotesPerNote}\uFF08\u8303\u56F4\uFF1A1-10\uFF09`).addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.maxGeneratedNotesPerNote).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxGeneratedNotesPerNote = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    containerEl.createEl("h3", { text: "\u81EA\u52A8\u5904\u7406\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u9996\u6B21\u542F\u52A8\u65F6\u6267\u884C\u5B8C\u6574\u521D\u59CB\u5316").setDesc("\u63D2\u4EF6\u9996\u6B21\u542F\u52A8\u65F6\u81EA\u52A8\u5206\u6790\u6240\u6709\u7B14\u8BB0\u5E76\u5EFA\u7ACB\u5173\u7CFB").addToggle((toggle) => toggle.setValue(true).setDisabled(true).onChange(async () => {
    }));
    new import_obsidian.Setting(containerEl).setName("\u542F\u52A8\u65F6\u81EA\u52A8\u521D\u59CB\u5316").setDesc("Obsidian \u542F\u52A8\u65F6\u81EA\u52A8\u6267\u884C\u5B8C\u6574\u521D\u59CB\u5316\u6D41\u7A0B\uFF08\u5206\u6790\u7B14\u8BB0 + \u5173\u7CFB\u626B\u63CF\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOrganizeOnStartup).onChange(async (value) => {
      this.plugin.settings.autoOrganizeOnStartup = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u521B\u5EFA\u7B14\u8BB0\u65F6\u81EA\u52A8\u5206\u6790").setDesc("\u521B\u5EFA\u65B0\u7B14\u8BB0\u65F6\u81EA\u52A8\u8C03\u7528 AI \u5206\u6790\u5185\u5BB9").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOrganizeOnCreate).onChange(async (value) => {
      this.plugin.settings.autoOrganizeOnCreate = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u4FEE\u6539\u7B14\u8BB0\u65F6\u81EA\u52A8\u5206\u6790").setDesc("\u4FEE\u6539\u7B14\u8BB0\u5185\u5BB9\u540E\u81EA\u52A8\u91CD\u65B0\u8C03\u7528 AI \u5206\u6790").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOrganizeOnModify).onChange(async (value) => {
      this.plugin.settings.autoOrganizeOnModify = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5206\u6790\u540E\u81EA\u52A8\u5EFA\u7ACB\u5173\u7CFB").setDesc("\u6279\u91CF\u5206\u6790\u7B14\u8BB0\u5B8C\u6210\u540E\u81EA\u52A8\u6267\u884C\u5168\u5C40\u5173\u7CFB\u626B\u63CF").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoRelationScanAfterOrganize).onChange(async (value) => {
      this.plugin.settings.autoRelationScanAfterOrganize = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u626B\u63CF\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u5168\u5C40\u5173\u8054\u5206\u6790").setDesc("\u91CD\u65B0\u626B\u63CF\u6240\u6709\u7B14\u8BB0\uFF0C\u5EFA\u7ACB\u8BED\u4E49\u5173\u8054\u5173\u7CFB").addButton((button) => button.setButtonText("\u6267\u884C\u5168\u5C40\u626B\u63CF").onClick(async () => {
      button.setButtonText("\u626B\u63CF\u4E2D...");
      button.setDisabled(true);
      await this.plugin.globalRelationScan();
      button.setButtonText("\u6267\u884C\u5168\u5C40\u626B\u63CF");
      button.setDisabled(false);
    }));
    new import_obsidian.Setting(containerEl).setName("\u542F\u52A8\u65F6\u4EC5\u6267\u884C\u5173\u7CFB\u626B\u63CF").setDesc("Obsidian \u542F\u52A8\u65F6\u4EC5\u6267\u884C\u5168\u5C40\u5173\u7CFB\u626B\u63CF\uFF08\u4E0D\u5206\u6790\u7B14\u8BB0\u5185\u5BB9\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoScanOnStartup).onChange(async (value) => {
      this.plugin.settings.autoScanOnStartup = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6279\u5904\u7406\u5927\u5C0F").setDesc(`\u6BCF\u6B21\u5904\u7406\u7684\u7B14\u8BB0\u6570\u91CF: ${this.plugin.settings.batchSize}`).addSlider((slider) => slider.setLimits(1, 50, 1).setValue(this.plugin.settings.batchSize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.batchSize = value;
      await this.plugin.saveSettings();
      this.display();
    })).addText((text) => text.setPlaceholder("\u8F93\u5165\u6570\u5B57").setValue(this.plugin.settings.batchSize.toString()).onChange(async (value) => {
      const num = parseInt(value, 10);
      if (!isNaN(num) && num >= 1 && num <= 50) {
        this.plugin.settings.batchSize = num;
        await this.plugin.saveSettings();
        this.display();
      } else {
        text.setValue(this.plugin.settings.batchSize.toString());
      }
    }).inputEl.style.width = "80px");
    new import_obsidian.Setting(containerEl).setName("\u6392\u9664\u6587\u4EF6\u5939").setDesc("\u626B\u63CF\u65F6\u6392\u9664\u7684\u6587\u4EF6\u5939\uFF08\u9017\u53F7\u5206\u9694\uFF09").addText((text) => text.setPlaceholder("templates, archive").setValue(this.plugin.settings.excludeFolders.join(", ")).onChange(async (value) => {
      this.plugin.settings.excludeFolders = value.split(",").map((s) => s.trim()).filter((s) => s);
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u63D2\u5165\u6458\u8981").setDesc("AI \u6574\u7406\u65F6\u81EA\u52A8\u63D2\u5165\u6458\u8981\u533A\u5757").addToggle((toggle) => toggle.setValue(this.plugin.settings.insertSummary).onChange(async (value) => {
      this.plugin.settings.insertSummary = value;
      await this.plugin.saveSettings();
    }));
  }
};
